services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: ${MQTT_HOST}
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:${MQTT_PORT}
    volumes:
      - ./docker/mosquitto:/etc/mosquitto
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - backend


  mongo:
    image: mongo:4
    hostname: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/mongodb:/data/db
    networks:
      - backend


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWD}@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWD}
    networks:
      - backend
      - frontend

  se-socket-ingester:
    image: se-socket-ingester:latest
    container_name: se-socket-ingester
    restart: on-failure:3
    depends_on:
      - digester
      - mosquitto
    environment:
      SE_CLIENT_JWT: ${JWT}
      SE_CLIENT_MQTT_HOST: ${MQTT_HOST}
      SE_CLIENT_MQTT_PORT: ${MQTT_PORT}
      SE_CLIENT_MQTT_USER: ${MQTT_USER}
      SE_CLIENT_MQTT_PASSWD: ${MQTT_PASSWD}
      SE_CLIENT_LOG_LEVEL: ${LOG_LEVEL}
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

  se-api-ingester:
    image: se-api-ingester:latest
    container_name: se-api-ingester
    restart: on-failure:3
    depends_on:
      - digester
      - mosquitto
    environment:
      SE_API_DATE_START: 2024-11-04T16:00.000Z
      SE_API_SLEEP: 300
      SE_API_REQUEST_WINDOW: 600
      SE_API_THROTTLE: 2
      SE_API_JWT: ${JWT}
      SE_API_MQTT_HOST: ${MQTT_HOST}
      SE_API_MQTT_PORT: ${MQTT_PORT}
      SE_API_MQTT_USER: ${MQTT_USER}
      SE_API_MQTT_PASSWD: ${MQTT_PASSWD}
      SE_API_LOG_LEVEL: ${LOG_LEVEL}
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

  digester:
    user: 1000:1000
    image: digester:latest
    container_name: digester
    restart: on-failure:5
    depends_on:
      - mongo
      - mosquitto
    environment:
      DIGESTER_MQTT_HOST: ${MQTT_HOST}
      DIGESTER_MQTT_PORT: ${MQTT_PORT}
      DIGESTER_MQTT_USER: ${MQTT_USER}
      DIGESTER_MQTT_PASSWD: ${MQTT_PASSWD}
      DIGESTER_LOG_LEVEL: ${LOG_LEVEL}
      DIGESTER_MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWD}@mongo:27017
    volumes:
      - ./docker/digester/config.yaml:/app/config.yaml
      - ./output/:/app/output/
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
